name: DreamActivity
version: '${version}'
main: ltd.dreamcraft.dreamactivity.DreamActivity
api-version: '1.18'
depend: [DreamPainter]
authors: [haishen668]
description: 一款绘梦师附属插件
website: www.dreamcraft.ltd
